# Generated by Django 4.2.4 on 2024-03-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
