# Generated by Django 4.2.4 on 2024-03-28 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landfill',
            fields=[
                ('landfill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('operational_timespan', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='STS',
            fields=[
                ('sts_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ward_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('open_truck', 'Open Truck'), ('dump_truck', 'Dump Truck'), ('compactor', 'Compactor'), ('container_carrier', 'Container Carrier')], max_length=20)),
                ('capacity', models.IntegerField(choices=[(3, '3 Ton'), (5, '5 Ton'), (7, '7 Ton')])),
                ('fuel_cost_loaded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_cost_unloaded', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='STSManager',
            fields=[
                ('sts_manager_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=100)),
                ('sts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.sts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='STSEntry',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_of_waste', models.IntegerField()),
                ('time_of_arrival', models.DateTimeField()),
                ('time_of_departure', models.DateTimeField()),
                ('sts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.sts')),
                ('sts_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.stsmanager')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='LandfillManager',
            fields=[
                ('landfill_manager_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=100)),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.landfill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandfillEntry',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_of_waste', models.IntegerField()),
                ('time_of_arrival', models.DateTimeField()),
                ('time_of_departure', models.DateTimeField()),
                ('landfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.landfill')),
                ('landfill_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.landfillmanager')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.vehicle')),
            ],
        ),
    ]
