# Generated by Django 4.2.4 on 2024-03-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_landfill_sts_vehicle_stsmanager_stsentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landfillmanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.user'),
        ),
        migrations.AlterField(
            model_name='stsmanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.user'),
        ),
    ]
