# Generated by Django 4.2.4 on 2024-03-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0007_alter_landfillmanager_user_alter_stsmanager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landfillmanager',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='stsmanager',
            name='manager_name',
        ),
    ]
