# Generated by Django 4.2.4 on 2024-03-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0008_remove_landfillmanager_manager_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(choices=[(3, '3 Ton'), (5, '5 Ton'), (7, '7 Ton'), (15, '15 Ton')]),
        ),
    ]
