# Generated by Django 4.2.4 on 2024-03-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0009_alter_vehicle_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
