# Generated by Django 4.2.4 on 2024-03-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0012_alter_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landfill',
            name='landfill_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sts',
            name='sts_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
