# Generated by Django 4.2.4 on 2024-03-30 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0013_alter_landfill_landfill_id_alter_sts_sts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landfill',
            name='landfill_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sts',
            name='sts_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
