# Generated by Django 4.2.4 on 2024-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0015_alter_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landfill',
            name='landfill_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sts',
            name='sts_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
