# Generated by Django 4.2.4 on 2024-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0016_alter_landfill_landfill_id_alter_sts_sts_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landfillentry',
            name='entry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stsentry',
            name='entry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
